from dlinkdcs import DlinkDCSCamera as ipcam
import os

#print(os.environ['HOME'])
# ref https://stackoverflow.com/questions/4906977/how-can-i-access-environment-variables-in-python. Below has same effect
CAM_HOST = os.environ.get('CAM_HOST') or ''
CAM_PORT = os.environ.get('CAM_PORT', 80)
CAM_USER = os.getenv('CAM_USER', 'admin')
CAM_PASS = os.getenv('CAM_PASS', '')

if CAM_HOST == '':
    print('Please set CAM_HOST environment variable')
    exit()
ipcam = ipcam(CAM_HOST, CAM_USER, CAM_PASS, CAM_PORT)
r = ipcam.get_cgi_version()
print(r)
r = ipcam.get_common_info()
print(r)
r = ipcam.get_date_time()
print(r)
r = ipcam.get_day_night()
print(r)
r = ipcam.get_email()
print(r)
r = ipcam.get_iimage()
print(r)
r = ipcam.get_image()
print(r)
r = ipcam.get_inetwork()
print(r)
r = ipcam.get_isystem()
print(r)
r = ipcam.get_iwireless()
print(r)
r = ipcam.get_motion_detection()
print(r)
r = ipcam.get_network()
print(r)
r = ipcam.get_ptz()
print(r)
r = ipcam.get_ptz_presets()
print(r)
r = ipcam.get_sound_detection()
print(r)
r = ipcam.get_stream_info()
print(r)
r = ipcam.get_user()
print(r)
r = ipcam.get_upload()
print(r)
r = ipcam.get_user_list()
print(r)
r = ipcam.set_ptz(100, 50, 0)
print(r)
r = ipcam.set_ptz()